const products = [
  {id:1,category:'women',name:'Set fluido negro',price:34400,sizes:'XS · S · M',image:'https://gaphant.com/cdn/shop/files/gaphant-uniformes-medicos-de-mujer-roma-negro-03_384x.webp?v=1759933494'},
  {id:2,category:'women',name:'Set lino natural',price:47900,sizes:'XS · S · M',image:'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=700&q=85'},
  {id:3,category:'women',name:'Pantalón wide leg',price:51700,sizes:'XS · S · M',image:'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?auto=format&fit=crop&w=700&q=85'},
  {id:4,category:'women',name:'Conjunto chocolate',price:44900,sizes:'XS · S · M',image:'https://images.unsplash.com/photo-1605763240000-7e93b172d754?auto=format&fit=crop&w=700&q=85'},
  {id:5,category:'women',name:'Chaleco blanco',price:56800,sizes:'XS · S · M',image:'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=700&q=85'},
  {id:6,category:'women',name:'Pantalón sastre',price:44500,sizes:'XS · S · M',image:'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=700&q=85'},
  {id:7,category:'men',name:'Camiseta Boston',price:16700,sizes:'S · M · L · XL',image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=700&q=85'},
  {id:8,category:'men',name:'Camisa urbana',price:16800,sizes:'S · M · L · XL',image:'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=700&q=85'},
  {id:9,category:'men',name:'Camisa negra',price:28400,sizes:'S · M · L · XL',image:'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=700&q=85'},
  {id:10,category:'men',name:'Pantalón cargo',price:46500,sizes:'S · M · L · XL',image:'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=700&q=85'},
  {id:11,category:'men',name:'Set monocromo',price:38800,sizes:'S · M · L · XL',image:'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=700&q=85'},
  {id:12,category:'teens',name:'Set street negro',price:25300,sizes:'Talla 4',image:'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=700&q=85'},
  {id:13,category:'teens',name:'Falda con vuelo',price:25700,sizes:'S · M · L',image:'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=700&q=85'},
  {id:14,category:'teens',name:'Top cut-out',price:10900,sizes:'S · M · L',image:'https://images.unsplash.com/photo-1566206091558-7f218b696731?auto=format&fit=crop&w=700&q=85'},
  {id:15,category:'teens',name:'Set deportivo rosa',price:19200,sizes:'S · M · L',image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIFdc8VPoXVm18fOBRAuiGp6k_WxO2flOejH-YOn69CA&s=10'},
  {id:16,category:'teens',name:'Top blanco fruncido',price:9200,sizes:'S · M · L',image:'https://images.unsplash.com/photo-1581044777550-4cfa60707c03?auto=format&fit=crop&w=700&q=85'},
  {id:17,category:'teens',name:'Set casual azul',price:60000,sizes:'12-13 años · 13-14 años',image:'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=700&q=85'},
  {id:18,category:'teens',name:'Look urbano',price:32700,sizes:'11-12 años · 14-15 años',image:'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=700&q=85'}
];
const categoryNames={women:'Mujer',men:'Hombre',teens:'Adolescentes'};
let activeCategory='all'; let cart=JSON.parse(localStorage.getItem('avyn-cart')||'[]');
const $=selector=>document.querySelector(selector);
const money=value=>`$${value.toLocaleString('es-CO')}`;
function renderProducts(){const query=$('#searchInput').value.toLowerCase().trim();const sort=$('#sortSelect').value;let visible=products.filter(p=>(activeCategory==='all'||p.category===activeCategory)&&(`${p.name} ${categoryNames[p.category]}`).toLowerCase().includes(query));if(sort==='low')visible.sort((a,b)=>a.price-b.price);if(sort==='high')visible.sort((a,b)=>b.price-a.price);$('#productGrid').innerHTML=visible.map((p,index)=>`<article class="product-card" style="animation-delay:${index*35}ms"><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy"><button class="quick-add" data-add="${p.id}" aria-label="Añadir ${p.name}">+</button></div><div class="product-meta"><p class="category-label">${categoryNames[p.category]}</p><h3>${p.name}</h3><div class="meta-line"><span class="price">${money(p.price)}</span><span class="sizes">${p.sizes}</span></div></div></article>`).join('');$('#emptyState').classList.toggle('hidden',visible.length>0);}
function renderCart(){const count=cart.reduce((sum,item)=>sum+item.quantity,0);$('#cartCount').textContent=count;$('#cartItems').innerHTML=cart.length?cart.map(item=>`<div class="cart-item"><img src="${item.image}" alt="${item.name}"><div><h4>${item.name}</h4><p>${item.sizes}</p><p>${money(item.price)} · ${item.quantity} ud.</p></div><button class="remove-item" data-remove="${item.id}" aria-label="Eliminar">×</button></div>`).join(''):'<p class="cart-empty">Tu carrito está esperando una nueva favorita.</p>';$('#cartTotal').textContent=money(cart.reduce((sum,item)=>sum+item.price*item.quantity,0));localStorage.setItem('avyn-cart',JSON.stringify(cart));}
function setCategory(category){activeCategory=category;document.querySelectorAll('[data-category]').forEach(button=>button.classList.toggle('active',button.dataset.category===category));renderProducts();}
function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200);}
function openCart(){ $('#cartDrawer').classList.add('open');$('#drawerBackdrop').classList.add('visible');$('#cartDrawer').setAttribute('aria-hidden','false');}
function closeCart(){ $('#cartDrawer').classList.remove('open');$('#drawerBackdrop').classList.remove('visible');$('#cartDrawer').setAttribute('aria-hidden','true');}
$('#authForm').addEventListener('submit',event=>{event.preventDefault();const user=$('#nameInput').value.trim();localStorage.setItem('avyn-user',user);startShop(user);});
function startShop(user){$('#authView').classList.add('hidden');$('#shopView').classList.remove('hidden');$('#welcomeUser').textContent=`Hola, ${user.split(' ')[0]}`;renderProducts();renderCart();}
document.addEventListener('click',event=>{const add=event.target.closest('[data-add]');if(add){const product=products.find(p=>p.id===Number(add.dataset.add));const existing=cart.find(item=>item.id===product.id);if(existing)existing.quantity++;else cart.push({...product,quantity:1});renderCart();showToast(`${product.name} añadido al carrito`);}const remove=event.target.closest('[data-remove]');if(remove){cart=cart.filter(item=>item.id!==Number(remove.dataset.remove));renderCart();}const category=event.target.closest('[data-category]');if(category)setCategory(category.dataset.category);});
$('#searchInput').addEventListener('input',renderProducts);$('#sortSelect').addEventListener('change',renderProducts);$('#cartButton').addEventListener('click',openCart);$('#closeCart').addEventListener('click',closeCart);$('#drawerBackdrop').addEventListener('click',closeCart);$('#exploreButton').addEventListener('click',()=>$('#catalogo').scrollIntoView());$('#logoutButton').addEventListener('click',()=>{localStorage.removeItem('avyn-user');$('#shopView').classList.add('hidden');$('#authView').classList.remove('hidden');});$('#checkoutButton').addEventListener('click',()=>showToast('Demo visual: el pago se conectará después.'));
const savedUser=localStorage.getItem('avyn-user');if(savedUser)startShop(savedUser);